name: "000_STRCNN_lr2e4_DVD_e651_B8G6_s"

dataset:
    train:
        name: "DVD"
        mode: "train"
        
        sampling: "strcnn"  # "n_n" and "n_c" , "n_l", "n_r", "n_c_m"
        overlapping: True
        interval: 1
        
        root_gt: "./datasets/DVD/quantitative_datasets"
        data_type: "imgs"
        num_frames: 12
        
        # augmentations
        augmentation:
            RandomCrop: 
                size : [256, 256]
            RandomHorizontalFlip: 
                p: 0.5
            RandomVerticalFlip: 
                p: 0.5
            RandomRotation90: 
                p: 0.5
            # RandomReverse: 
            #     p: 0.5
            ToTensor: True
        
        loader:
            batch_size: 8
            num_workers: 10
            

    val:
        name: "DVD"
        mode: "val"
        
        sampling: "strcnn"  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: False 
        interval: 1
        
        root_gt: "./datasets/DVD/test"
        data_type: "imgs"
        num_frames: 12

        loader:
            batch_size: 1
            num_workers: 2
    
    test:
        name: "DVD"
        mode: "val"
        
        sampling: "strcnn"  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: False 
        interval: 1
        
        root_gt: "./datasets/DVD/test"
        data_type: "imgs"
        num_frames: 12

        loader:
            batch_size: 1
            num_workers: 2


model:
    name: "STRCNN"
    num_frames_encoded: 5
    in_channels: 3
    inner_channels: 32
    encoder_blocks: 4
    decoder_blocks: 4
    is_dtb: True

loss: 
    name: CharbonnierLoss

schedule: 
    epochs: 651
    val_epochs: 5
    
    optimizer:
        name: "Adam"
        lr: 0.0002
        betas: [0.9, 0.99]
        weight_decay: 0
        
    lr_scheduler:
        name: "MultiStepLR"
        milestones: [500, 600, 620]
        gamma: 0.1

logging: 
    period: 20

ckpt:
    period: 10


work_dir: "./workdir/strcnn"
resume_from: None