name: "000_cdvdtsp_lr2e4_REDS_e401_B4G2_s"

__base_cfg__: ./../base_reds.yaml

dataset:
    train:
        # dataloader per GPU
        loader:
            batch_size: 4
            num_workers: 4

model:
    name: "CDVD_TSP"
    in_channels: 3
    n_sequence: 5
    out_channels: 3
    n_resblock: 3
    n_feat: 32
    load_flow_net: True
    load_recons_net: False
    flow_pretrain_fn: ""
    recons_pretrain_fn: ""
    is_mask_filter: True

loss: 
    criterion:
    - name: HEM
    hard_thre_p: 0.5
    random_thre_p: 0.1
    
    weights: 
    - 1.0

schedule: 
    epochs: 401
    val_epochs: 2
    
    optimizer:
        name: "Adam"
        lr: !!float 1e-4
        betas: [0.9, 0.999]
        weight_decay: 0
        
    lr_scheduler:
        name: "MultiStepLR"
        milestones: [300, 350, 380]
        gamma: 0.1

logging: 
    period: 20

ckpt:
    period: 10



work_dir: "./workdir/CDVD_TSP"
resume_from: None