name: "000_STFAN_seq20_lr2e4_DVD_e651_B1G2_s"

dataset:
    train:
        name: DVD
        mode: train
        
        sampling: n_n  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: True
        interval: 1
        
        root_gt: ./datasets/DVD/quantitative_datasets
        data_type: "imgs"
        num_frames: 20
        
        # augmentations
        augmentation:
            RandomCrop: 
                size : [256, 256]
            RandomHorizontalFlip: 
                p: 0.5
            RandomVerticalFlip: 
                p: 0.5
            RandomRotation90: 
                p: 0.5
            RandomReverse: 
                p: 0.5
        # dataloader per GPU
        loader:
            batch_size: 2
            num_workers: 8
            

    val:
        name: "DVD"
        mode: "val"
        
        sampling: n_n  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: False
        interval: 1
        
        root_gt: "./datasets/DVD/test"
        data_type: "imgs"
        num_frames: 5

        loader:
            batch_size: 1
            num_workers: 1
    
    test:
        name: "DVD"
        mode: "val"
        
        sampling: "n_n"  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: Fasle
        interval: 1
        
        root_gt: "./datasets/DVD/quantitative_datasets"
        data_type: "imgs"
        num_frames: 5

        loader:
            batch_size: 1
            num_workers: 2


meta_arch: STFANRNNArch
model:
    name: STFANCell

loss: 
    name: CharbonnierLoss

schedule: 
    epochs: 651
    val_epochs: 5
    
    optimizer:
        name: "Adam"
        lr: 0.0001
        betas: [0.9, 0.99]
        weight_decay: 0
        
    lr_scheduler:
        name: "MultiStepLR"
        milestones: [500, 600, 620]
        gamma: 0.1

logging: 
    period: 20

ckpt:
    period: 10


work_dir: "./workdir/stfan"
resume_from: None