name: "000_STFAN_seq20_lr2e4_REDS_e401_B1G2_s"

__base_cfg__: ./../base_reds.yaml

dataset:
    train:
        sampling: "n_n"  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: True

        num_frames: 20

        # dataloader per GPU
        loader:
            batch_size: 2
            num_workers: 8
            

    val:
        sampling: "n_n"  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: False

        num_frames: 20

        loader:
            batch_size: 1
            num_workers: 1
    
    test:
        sampling: "n_n"  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: False

        num_frames: 20

        loader:
            batch_size: 1
            num_workers: 1


meta_arch: STFANRNNArch
model:
    name: STFANCell

loss:
    criterion:
      - name: MSELoss
      - name: PerceptualLossVGG19
        reduction: mean
    
    weights:
    - 1.0
    - 0.01

schedule: 
    epochs: 401
    val_epochs: 2
    
    optimizer:
        name: "Adam"
        lr: 0.0001
        betas: [0.9, 0.999]
        weight_decay: 0
        
    lr_scheduler:
        name: "MultiStepLR"
        milestones: [300, 350, 380]
        gamma: 0.1

logging: 
    period: 20

ckpt:
    period: 10


work_dir: "./workdir/stfan"
resume_from: None