name: "000_STFAN_seq20_lr2e4_GOPRO_e1001_B1G2_s"

__base_cfg__: ./../base_gopro.yaml

dataset:
    train:
        sampling: n_n

        use_gamma: False
        num_frames: 20
        # dataloader per GPU
        loader:
            batch_size: 1
            num_workers: 1
    
    val:
        sampling: n_n
        overlapping: False

        root_gt: "./datasets/GOPRO/test"
        use_gamma: True
        num_frames: 3

meta_arch: STFANRNNArch
model:
    name: STFANCell

loss:
    criterion:
      - name: MSELoss
      - name: PerceptualLossVGG19
        reduction: mean
    
    weights:
    - 1.0
    - 0.01

schedule: 
    epochs: 1001
    val_epochs: 10
    
    optimizer:
        name: "Adam"
        lr: 0.0001
        betas: [0.9, 0.999]
        weight_decay: 0
        
    lr_scheduler:
        name: "MultiStepLR"
        milestones: [700, 850, 920]
        gamma: 0.1

logging: 
    period: 20

ckpt:
    period: 10


work_dir: "./workdir/stfan"
resume_from: None