name: 000_NAFNet_lr2e4_GoPro_e1001_B8G1_s

__base_cfg__: ./../base_gopro.yaml

dataset:
    train:
        sampling: n_n

        num_frames: 1
        # dataloader per GPU
        loader:
            batch_size: 1
            num_workers: 1
    
    val:
        sampling: n_n
        num_frames: 1

meta_arch: "SingleScalePlainCNN"
model:
    name: NAFNet
    width: 64
    enc_blk_nums: [1, 1, 1, 28]
    middle_blk_num: 1
    dec_blk_nums: [1, 1, 1, 1]

loss:
    criterion:
      - name: CharbonnierLoss
    
    weights: [1.0]

schedule: 
    epochs: 1001
    val_epochs: 10
    
    optimizer:
        name: "Adam"
        lr: 0.0002
        betas: [0.9, 0.99]
        weight_decay: 0
        
    lr_scheduler:
        name: "MultiStepLR"
        milestones: [700, 850, 920]
        gamma: 0.1


logging: 
    period: 20

ckpt:
    period: 10


work_dir: "./workdir/image_deblurring/nafnet"
resume_from: None