name: "000_PVDNet_lr2e4_REDS_e401_B8G1_s"

__base_cfg__: ./../base_reds.yaml

dataset:
    train:
        sampling: n_n
        overlapping: False

        use_gamma: False
        num_frames: 13
        # dataloader per GPU
        loader:
            batch_size: 4
            num_workers: 4
    
    val:
        sampling: n_n
        overlapping: False

        use_gamma: True
        num_frames: 50

meta_arch: PVDNetArch
model:
    name: PVDNet
    large_model: True
    bimnet_ckpt_path: ./workdir/pvdnet/ckpt/BIMNet.pytorch

loss:
    criterion:
      - name: CharbonnierLoss 
    
    weights: [1.0]

schedule: 
    epochs: 401
    val_epochs: 2
    
    optimizer:
        name: "Adam"
        lr: !!float 1e-4
        betas: [0.9, 0.999]
        weight_decay: 0
        
    lr_scheduler:
        name: "MultiStepLR"
        milestones: [300, 350, 380]
        gamma: 0.1

logging: 
    period: 20

ckpt:
    period: 10


work_dir: ./workdir/pvdnet
resume_from: None